# Generated by Django 5.1.6 on 2025-02-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='atmic_mass',
            new_name='atomic_mass',
        ),
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='element',
            name='family',
            field=models.PositiveIntegerField(verbose_name='族'),
        ),
        migrations.AlterField(
            model_name='element',
            name='number',
            field=models.PositiveIntegerField(verbose_name='元素番号'),
        ),
        migrations.AlterField(
            model_name='element',
            name='period',
            field=models.PositiveIntegerField(verbose_name='周期'),
        ),
    ]
