# Generated by Django 5.1.6 on 2025-02-12 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(default='preparation', max_length=10, verbose_name='戦闘状態')),
                ('pure_substance_deck', models.JSONField(default=list, verbose_name='山札')),
                ('turn', models.IntegerField(default=0, verbose_name='ターン数')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='player.player', verbose_name='勝者')),
            ],
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('player1', 'プレイヤー1'), ('player2', 'プレイヤー2')], max_length=10, verbose_name='役割')),
                ('life', models.IntegerField(default=100, verbose_name='ライフ')),
                ('energy', models.IntegerField(default=40, verbose_name='エネルギー')),
                ('nature_hand', models.JSONField(default=list, verbose_name='自然手札')),
                ('tool_hand', models.JSONField(default=list, verbose_name='化学道具手札')),
                ('tool_deck_copy', models.JSONField(default=list, verbose_name='化学道具デッキ（コピー）')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='battle.battle')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
            ],
        ),
    ]
