# Generated by Django 5.1.6 on 2025-02-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='state',
            field=models.CharField(default='preparation', max_length=20, verbose_name='戦闘状態'),
        ),
    ]
