# Generated by Django 5.1.6 on 2025-02-12 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='カードタイプ')),
                ('name', models.CharField(max_length=30, verbose_name='カード名')),
                ('cost', models.IntegerField(default=1, verbose_name='コスト')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='説明')),
                ('symbol', models.CharField(max_length=3, verbose_name='元素記号')),
                ('number', models.PositiveIntegerField(verbose_name='元素番号')),
                ('atomic_mass', models.FloatField(verbose_name='原子量')),
                ('period', models.PositiveIntegerField(verbose_name='周期')),
                ('family', models.PositiveIntegerField(verbose_name='族')),
                ('properties', models.CharField(max_length=30, verbose_name='性質')),
                ('image', models.ImageField(blank=True, null=True, upload_to='element/image/', verbose_name='画像')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PureSubstanceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='カードタイプ')),
                ('name', models.CharField(max_length=30, verbose_name='カード名')),
                ('cost', models.IntegerField(default=1, verbose_name='コスト')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='説明')),
                ('atomic_mass', models.FloatField(verbose_name='原子量')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='カードタイプ')),
                ('name', models.CharField(max_length=30, verbose_name='カード名')),
                ('cost', models.IntegerField(default=1, verbose_name='コスト')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='説明')),
                ('effect', models.TextField(max_length=200, verbose_name='効果')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PureSubstanceElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='個数')),
                ('PureSubstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PureSubstance_elements', to='card.puresubstancecard', verbose_name='複合カード')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_PureSubstances', to='card.elementcard', verbose_name='構成元素')),
            ],
        ),
        migrations.AddField(
            model_name='puresubstancecard',
            name='elements',
            field=models.ManyToManyField(through='card.PureSubstanceElement', to='card.elementcard', verbose_name='構成元素'),
        ),
    ]
